version: '3.7'

services:
  db-postgres-test:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'usdc-transfer-test'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: '12345678'
      PGDATA: /data/postgres
    ports:
      - '5452:5432'
    expose:
      - '5452'
    volumes:
      - postgres-db-test:/data/postgres

  backend-usdc-transfer-test:
    container_name: backend-usdc-transfer-test
    build:
      context: .
      target: testing
      args:
        - NODE_ENV=test
    environment:
      DATABASE_URL: 'postgresql://user:12345678@db-postgres-test:5432/usdc-transfer-test'
    depends_on:
      - db-postgres-test

volumes:
  postgres-db-test: