version: '3.7'

services:
  db-postgres-dev:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'usdc-transfer-dev'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: '12345678'
      PGDATA: /data/postgres
    ports:
      - '5442:5432'
    expose:
      - '5432'
    volumes:
      - postgres-db-dev:/data/postgres

  backend-usdc-transfer-dev:
    container_name: backend-usdc-transfer-dev
    build:
      context: .
      target: development
      args:
        - NODE_ENV=development
    environment:
      DATABASE_URL: 'postgresql://user:12345678@db-postgres-dev:5432/usdc-transfer-dev'
    restart: always
    ports:
      - "3008:3001"
    expose:
      - '3307'
    depends_on:
      - db-postgres-dev

volumes:
  postgres-db-dev: